/**
 * Bank soal IPAS Kelas 3 SD
 * q  : pertanyaan
 * k  : kunci jawaban (benar)
 * o  : pilihan jawaban
 * e  : edukasi / penjelasan singkat (opsional)
 */
const QUESTION_BANK = {
    mudah: [
        { q: "Alat indera untuk melihat adalah ...", k: "Mata", o: ["Telinga", "Mata", "Hidung", "Kaki"] },
        { q: "Bagian tumbuhan yang menyerap air dari tanah adalah ...", k: "Akar", o: ["Batang", "Daun", "Akar", "Bunga"] },
        { q: "Alat untuk mengukur suhu tubuh adalah ...", k: "Termometer", o: ["Termometer", "Barometer", "Meteran", "Timbangan"] },
        { q: "Hewan yang hidup di air dan bernapas dengan insang adalah ...", k: "Ikan", o: ["Ayam", "Kucing", "Ikan", "Sapi"] },
        { q: "Hewan yang pemakan tumbuhan (herbivora) adalah ...", k: "Sapi", o: ["Harimau", "Sapi", "Elang", "Ular"] },
        { q: "Tumbuhan penghasil beras adalah ...", k: "Padi", o: ["Jagung", "Padi", "Tebu", "Singkong"] },
        { q: "Alat indera untuk mencium bau adalah ...", k: "Hidung", o: ["Telinga", "Hidung", "Bibir", "Kuku"] },
        { q: "Cairan tubuh yang berwarna merah adalah ...", k: "Darah", o: ["Darah", "Keringat", "Air liur", "Susu"] },
        { q: "Alat pernapasan manusia adalah ...", k: "Paru-paru", o: ["Jantung", "Paru-paru", "Lambung", "Ginjal"] },
        { q: "Udara masuk ke tubuh kita melalui ...", k: "Hidung", o: ["Telinga", "Hidung", "Kaki", "Tangan"] },
        { q: "Makanan pokok masyarakat Indonesia adalah ...", k: "Nasi", o: ["Roti", "Nasi", "Kentang", "Kue"] },
        { q: "Sayur yang berwarna oranye dan kaya vitamin A adalah ...", k: "Wortel", o: ["Bayam", "Wortel", "Kangkung", "Sawi"] },
        { q: "Gotong royong berarti ...", k: "Bekerja bersama-sama", o: ["Bekerja sendiri", "Bekerja bersama-sama", "Bermain-main", "Tidur siang"] },
        { q: "Ibu kota negara Indonesia adalah ...", k: "Jakarta", o: ["Bandung", "Surabaya", "Jakarta", "Medan"] },
        { q: "Alat transportasi di jalan raya adalah ...", k: "Mobil", o: ["Perahu", "Mobil", "Kapal", "Gondola"] },
        { q: "Wujud benda yang keras dan bentuknya tetap adalah ...", k: "Padat", o: ["Cair", "Gas", "Padat", "Uap"] },
        { q: "Es batu yang diletakkan di tempat panas akan ...", k: "Mencair", o: ["Membeku", "Mencair", "Menguap", "Mengeras"] },
        { q: "Hewan yang berkembang biak dengan bertelur adalah ...", k: "Ayam", o: ["Kambing", "Sapi", "Ayam", "Anjing"] },
        { q: "Alat untuk melihat benda yang jauh adalah ...", k: "Teropong", o: ["Kaca pembesar", "Teropong", "Penggaris", "Kompas"] },
        { q: "Perkiraan cuaca disebut ...", k: "Prakiraan cuaca", o: ["Prakiraan cuaca", "Pengukuran tanah", "Peta wilayah", "Prakiraan bencana"] },
        { q: "Cuaca ketika matahari bersinar terang adalah ...", k: "Cerah", o: ["Hujan", "Cerah", "Badai", "Salju"] },
        { q: "Alat indera untuk merasakan masakan adalah ...", k: "Lidah", o: ["Lidah", "Kuku", "Rambut", "Telinga"] },
        { q: "Alat indera untuk mendengar adalah ...", k: "Telinga", o: ["Telinga", "Hidung", "Mata", "Mulut"] },
        { q: "Ibu yang menanam padi di sawah disebut ...", k: "Petani", o: ["Dokter", "Petani", "Guru", "Pilot"] },
        { q: "Hewan yang hidup di air tawar adalah ...", k: "Katak", o: ["Katak", "Hiu", "Paus", "Penyu"] },
        { q: "Buah yang berwarna kuning dan disukai kera adalah ...", k: "Pisang", o: ["Duren", "Pisang", "Manggis", "Salak"] },
        { q: "Menjaga kebersihan lingkungan berarti ...", k: "Membuang sampah pada tempatnya", o: ["Membiarkan sampah", "Membuang sampah pada tempatnya", "Membakar sampah di sembarang tempat", "Menumpuk sampah di kelas"] },
        { q: "Bagian tumbuhan yang berwarna hijau untuk berfotosintesis adalah ...", k: "Daun", o: ["Akar", "Daun", "Bunga", "Buah"] }
    ],

    sedang: [
        { q: "Penyerap sari-sari makanan di dalam tubuh adalah ...", k: "Usus halus", o: ["Lambung", "Kerongkongan", "Usus halus", "Mulut"] },
        { q: "Organ penyaring darah dan pembuang kotoran tubuh adalah ...", k: "Ginjal", o: ["Ginjal", "Jantung", "Paru-paru", "Lambung"] },
        { q: "Organ yang berfungsi memompa darah ke seluruh tubuh adalah ...", k: "Jantung", o: ["Paru-paru", "Jantung", "Otak", "Hati"] },
        { q: "Planet yang paling dekat dengan matahari adalah ...", k: "Merkurius", o: ["Venus", "Bumi", "Merkurius", "Mars"] },
        { q: "Satelit alami bumi kita adalah ...", k: "Bulan", o: ["Mars", "Bulan", "Jupiter", "Matahari"] },
        { q: "Perubahan wujud gas menjadi padat disebut ...", k: "Menyublim", o: ["Mencair", "Mengembun", "Menguap", "Menyublim"] },
        { q: "Perubahan wujud gas menjadi cair disebut ...", k: "Mengembun", o: ["Membeku", "Mengembun", "Mencair", "Menyublim"] },
        { q: "Air yang berubah menjadi uap karena panas matahari disebut ...", k: "Menguap", o: ["Menguap", "Membeku", "Mengembun", "Menyublim"] },
        { q: "Alat pernapasan ikan adalah ...", k: "Insang", o: ["Paru-paru", "Insang", "Kulit", "Trakea"] },
        { q: "Lapisan bumi tempat manusia tinggal disebut ...", k: "Kerak bumi", o: ["Inti bumi", "Kerak bumi", "Lapisan ozon", "Awan"] },
        { q: "Bagian bumi yang sangat panas dan berupa cairan adalah ...", k: "Magma", o: ["Magma", "Lautan", "Tanah subur", "Angin"] },
        { q: "Tumbuhan membuat makanan dari ...", k: "Air dan karbon dioksida", o: ["Air dan oksigen", "Air dan karbon dioksida", "Gula dan garam", "Tanah dan batu"] },
        { q: "Tumbuhan mengeluarkan oksigen pada waktu ...", k: "Siang hari", o: ["Malam hari", "Siang hari", "Tengah malam", "Subuh yang gelap"] },
        { q: "Pembangkit listrik tenaga air disingkat ...", k: "PLTA", o: ["PLTU", "PLTA", "PLTS", "Pabrik"] },
        { q: "Gravitasi bumi membuat benda ...", k: "Jatuh ke bumi", o: ["Melayang", "Terbang ke luar angkasa", "Jatuh ke bumi", "Menghilang"] },
        { q: "Bumi berputar pada porosnya disebut ...", k: "Rotasi", o: ["Revolusi", "Rotasi", "Getaran", "Denyut"] },
        { q: "Bumi mengelilingi matahari disebut ...", k: "Revolusi", o: ["Rotasi", "Revolusi", "Meluncur", "Berputar"] },
        { q: "Makanan sumber protein nabati adalah ...", k: "Tahu", o: ["Nasi", "Tahu", "Roti", "Kentang"] },
        { q: "Makanan sumber protein hewani adalah ...", k: "Telur", o: ["Tempe", "Wortel", "Telur", "Kangkung"] },
        { q: "Semua makhluk hidup pasti ...", k: "Tumbuh dan berkembang biak", o: ["Tumbuh dan berkembang biak", "Bisa terbang", "Selalu keras", "Tidak bergerak"] },
        { q: "Pada jaring-jaring makanan, yang berada di urutan pertama (produsen) adalah ...", k: "Tumbuhan hijau", o: ["Tumbuhan hijau", "Ulat", "Ayam", "Elang"] },
        { q: "Kambing hidup di lingkungan ...", k: "Padang rumput", o: ["Laut", "Sungai", "Padang rumput", "Kolam"] },
        { q: "Negara yang berbatasan langsung dengan Indonesia di Pulau Kalimantan adalah ...", k: "Malaysia", o: ["Jepang", "Malaysia", "Korea", "Mesir"] },
        { q: "Alat bantu peta untuk menunjukkan arah adalah ...", k: "Kompas", o: ["Kompas", "Penggaris", "Kaca pembesar", "Termometer"] },
        { q: "Gambar permukaan bumi yang dilihat dari atas disebut ...", k: "Peta", o: ["Foto", "Peta", "Lukisan", "Cermin"] },
        { q: "Sebelum hujan, biasanya langit menjadi ...", k: "Mendung", o: ["Cerah", "Mendung", "Berbintang", "Terang"] },
        { q: "Makanan pertama kali dikunyah di ...", k: "Mulut", o: ["Lambung", "Usus", "Mulut", "Kerongkongan"] },
        { q: "Pakaian yang cocok digunakan saat hujan adalah ...", k: "Jas hujan", o: ["Jas hujan", "Kaos tipis", "Sandal", "Pakaian renang"] }
    ],

    sulit: [
        { q: "Mengapa pada malam hari tempat kita menjadi gelap?", k: "Karena bumi berputar pada porosnya", o: ["Karena matahari padam", "Karena bumi berputar pada porosnya", "Karena awan menutupi matahari", "Karena bulan menutup matahari"] },
        { q: "Planet yang berukuran terbesar di tata surya adalah ...", k: "Jupiter", o: ["Bumi", "Mars", "Jupiter", "Merkurius"] },
        { q: "Jika hutan banyak ditebang, dampak yang paling mungkin terjadi adalah ...", k: "Banjir dan tanah longsor", o: ["Banjir dan tanah longsor", "Udara menjadi lebih sejuk", "Tanah menjadi makin subur", "Hewan bertambah banyak"] },
        { q: "Fungsi tulang rusuk pada tubuh manusia adalah ...", k: "Melindungi jantung dan paru-paru", o: ["Membantu berjalan", "Mengunyah makanan", "Melindungi jantung dan paru-paru", "Mendengar suara"] },
        { q: "Kandungan gizi yang berguna untuk menyehatkan tulang dan gigi adalah ...", k: "Kalsium", o: ["Kalsium", "Vitamin C", "Gula", "Lemak"] },
        { q: "Makanan yang dikunyah sampai halus membantu ...", k: "Memudahkan lambung mencerna makanan", o: ["Memudahkan lambung mencerna makanan", "Membuat badan gemuk", "Menambah warna makanan", "Menghemat waktu tidur"] },
        { q: "Lava adalah ...", k: "Cairan panas yang keluar dari gunung berapi", o: ["Cairan panas yang keluar dari gunung berapi", "Air hujan di puncak gunung", "Angin panas di gurun", "Debu vulkanik dingin"] },
        { q: "Jika sawah tidak diairi pada musim kemarau, padi akan ...", k: "Kering dan mati", o: ["Tumbuh lebih subur", "Kering dan mati", "Berubah menjadi jagung", "Menjadi lebih banyak"] },
        { q: "Hewan yang melahirkan dan menyusui anaknya adalah ...", k: "Kucing", o: ["Ayam", "Kucing", "Kupu-kupu", "Bebek"] },
        { q: "Hubungan antara kupu-kupu dan bunga (kupu-kupu mengambil madu, bunga terbantu penyerbukan) disebut ...", k: "Saling menguntungkan", o: ["Saling menguntungkan", "Merugikan satu pihak", "Tidak berhubungan", "Parasitisme"] },
        { q: "Pengurai sisa makhluk hidup di tanah berupa ...", k: "Jamur dan bakteri", o: ["Jamur dan bakteri", "Ulat dan belalang", "Elang dan ular", "Kucing dan anjing"] },
        { q: "Pada jaring-jaring makanan sawi → ulat → ayam → elang, produsennya adalah ...", k: "Sawi", o: ["Sawi", "Ulat", "Ayam", "Elang"] },
        { q: "Lampu senter menjadi redup karena ...", k: "Energi listrik pada baterai berkurang", o: ["Baterai menjadi lebih banyak", "Energi listrik pada baterai berkurang", "Lampu menjadi gemuk", "Kabel terlalu panjang"] },
        { q: "Bahan yang paling mudah menghantarkan panas adalah ...", k: "Logam", o: ["Kayu", "Karet", "Logam", "Plastik"] },
        { q: "Benda yang akan tertarik jika didekatkan ke magnet adalah ...", k: "Paku besi", o: ["Paku besi", "Kertas", "Kayu", "Kaca"] },
        { q: "Magnet memiliki dua kutub yaitu ...", k: "Kutub utara dan kutub selatan", o: ["Timur dan barat", "Kanan dan kiri", "Kutub utara dan kutub selatan", "Panas dan dingin"] },
        { q: "Bagian peta yang menjelaskan arti simbol-simbol disebut ...", k: "Keterangan peta", o: ["Keterangan peta", "Judul peta", "Neraca peta", "Sumber data"] },
        { q: "Indonesia terletak di sekitar garis khatulistiwa sehingga suhunya ...", k: "Panas sepanjang tahun", o: ["Dingin sepanjang tahun", "Panas sepanjang tahun", "Bersalju", "Empat musim"] },
        { q: "Mengapa air laut rasanya asin?", k: "Karena mengandung garam", o: ["Karena mengandung garam", "Karena mengandung es", "Karena mengandung sabun", "Karena mengandung minyak"] },
        { q: "Mentega yang diletakkan di wajan panas akan ...", k: "Mencair", o: ["Mencair", "Membeku", "Mengembun", "Menyublim"] },
        { q: "Saat gempa bumi, tindakan yang paling aman adalah ...", k: "Berlindung di bawah meja yang kuat", o: ["Berlindung di bawah meja yang kuat", "Berdiri di dekat jendela kaca", "Naik ke atap rumah", "Berdiri di dekat lemari kaca"] },
        { q: "Kita tidak dapat melihat benda di ruangan gelap karena ...", k: "Tidak ada cahaya", o: ["Tidak ada cahaya", "Mata kita terlalu kecil", "Benda terlalu jauh", "Udara terlalu dingin"] },
        { q: "Tumbuhan kaktus hidup dengan baik di daerah yang ...", k: "Kering dan sedikit hujan", o: ["Basah dan lembap", "Kering dan sedikit hujan", "Banyak air menggenang", "Bertopanan es"] },
        { q: "Salah satu cara menjaga kesehatan pencernaan adalah ...", k: "Mengunyah makanan sampai halus", o: ["Mengunyah makanan sampai halus", "Makan sambil berlari", "Melewatkan sarapan", "Makan terlalu cepat tanpa mengunyah"] },
        { q: "Mengapa daun pohon banyak berjatuhan pada musim kemarau?", k: "Untuk mengurangi penguapan air", o: ["Untuk mengurangi penguapan air", "Karena daun sudah bosan", "Karena daun ingin terbang", "Karena tanah terlalu dingin"] },
        { q: "Urutan peristiwa yang benar saat hujan terjadi adalah ...", k: "Penguapan → awan → turun sebagai hujan", o: ["Turun hujan → awan → penguapan", "Penguapan → awan → turun sebagai hujan", "Awan → penguapan → hujan beku", "Hujan → penguapan → awan"] },
        { q: "Peristiwa alam yang dapat diakibatkan oleh aktivitas manusia seperti menebang hutan adalah ...", k: "Erosi dan longsor", o: ["Erosi dan longsor", "Matahari terbit", "Pasang surut air laut", "Gerhana bulan"] }
    ]
};
